# Configuration Prometheus Stack - SANS OPERATOR
prometheus:
  server:
    retention: 15d
    persistentVolume:
      enabled: true
      storageClassName: local-path
      size: 10Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
  ingress:
    enabled: false

grafana:
  # Ingress désactivé - géré centralement
  adminPassword: "final.fantasy.7"  
  ingress:
    enabled: false
  
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi

alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
  ingress:
    enabled: false

prometheusOperator:
  enabled: true
  manageCrds: 

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: true
